version: '3.7'


services:
  web:
    build: /home/bishal/Desktop/newdir/docker_django/
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - /home/bishal/Desktop/newdir/docker_django /home/bishal/docker_project
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
  db:
    image: postgres:12.0-alpine
    ports:
      - "5432"
    volumes:
      - postgres_data:/home/bishal/docker_project/postgres_data/data/
    environment:
      - POSTGRES_USER=hello_django
      - POSTGRES_PASSWORD=hello_django
      - POSTGRES_DB=hello_django_dev

volumes:
  postgres_data:

