
version: '3.7'


services:
  web:
    build: 
      context: /home/bishal/Desktop/newdir/docker_django/
      dockerfile: Dockerfile.prod
    command: gunicorn project.wsgi:application --bind 0.0.0.0:8000
    ports:
      - 8000:8000
    env_file:
      - ./.env.prod
    depends_on:
      - db
  db:
    image: postgres:12.0-alpine
    ports:
      - "5432"
    volumes:
      - postgres_data:/home/bishal/docker_project/postgres_data/data/ 
    env_file:
      - ./.env.prod.db
volumes:
  postgres_data:

